//
//  ImageURL.swift
//  CatFacts
//
//  Created by Louise Verbeke on 06/05/2026.
//
struct ImageURL {
    // ImageURL.breedImages will return a dictionary with the key, a String, that will return another string, which is a URL to show an image of that breed.
    static let breedImages: [String: String] = [
        "Abyssinian": "https://upload.wikimedia.org/wikipedia/commons/9/9b/Gustav_chocolate.jpg",
        "Aegean": "https://upload.wikimedia.org/wikipedia/commons/5/51/Aegean_cat.jpg",
        "American Bobtail": "https://cattime.com/wp-content/uploads/sites/14/2011/12/GettyImages-530252495-e1706299449708.jpg?w=500",
        "American Curl": "https://cattime.com/wp-content/uploads/sites/14/2011/12/GettyImages-1431703484-e1701044466433.jpg?w=500",
        "American Shorthair": "https://upload.wikimedia.org/wikipedia/commons/0/0c/American_Shorthair.jpg",
        "American Wirehair": "https://cattime.com/wp-content/uploads/sites/14/2011/12/GettyImages-1094826686-e1703875084809.jpg?w=500",
        "Arabian Mau": "https://cattime.com/wp-content/uploads/sites/14/2024/01/GettyImages-629675330-e1705089514842.jpg?w=500",
        "Asian": "https://cattime.com/wp-content/uploads/sites/14/2020/05/GettyImages-589049206-e1706298857239.jpg?w=500",
        "Asian Semi-longhair": "https://commons.wikimedia.org/wiki/Special:FilePath/Tiffanie%20at%20cat%20show.jpg",
        "Australian Mist": "https://upload.wikimedia.org/wikipedia/commons/f/f0/Australian_Mist.jpg",
        "Balinese": "https://cattime.com/wp-content/uploads/sites/14/2011/12/GettyImages-1126736839-e1700062536195.jpg?w=500",
        "Bambino": "https://cattime.com/wp-content/uploads/sites/14/2020/01/GettyImages-639291894-e1704312933774.jpg?w=500",
        "Bengal": "https://cattime.com/wp-content/uploads/sites/14/2011/12/GettyImages-1343915455-e1696560859248.jpg?w=500",
        "Birman": "https://cattime.com/wp-content/uploads/sites/14/2011/12/GettyImages-136766072-e1704995345129.jpg?w=500",
        "Bombay": "https://cattime.com/wp-content/uploads/sites/14/2023/11/GettyImages-1226783086-e1701304000519.jpg?w=500",
        "Brazilian Shorthair": "https://cattime.com/wp-content/uploads/sites/14/2011/12/GettyImages-1361394182-e1699287824483.jpg?w=500",
        "British Longhair": "https://upload.wikimedia.org/wikipedia/commons/5/50/British_Longhair_-_Black_Silver_Shaded.jpg",
        "British Semi-longhair": "https://commons.wikimedia.org/wiki/Special:FilePath/British%20Semi-longhair.jpg",
        "British Shorthair": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Britishblue.jpg",
        "Burmese": "https://cattime.com/wp-content/uploads/sites/14/2011/12/GettyImages-1144180802-e1698431271496.jpg?w=500",
        "Burmilla": "https://cattime.com/wp-content/uploads/sites/14/2011/12/GettyImages-182783076-e1705090595355.jpg?w=500",
        "California Spangled": "https://cattime.com/wp-content/uploads/sites/14/2020/01/california-spangled-mixed-cat-breed-pictures-cover.jpg?w=500",
        "Chantilly-Tiffany": "https://cattime.com/wp-content/uploads/sites/14/2020/03/Tiffany4-e1703188484284.jpg?w=500",
        "Chartreux": "https://cattime.com/wp-content/uploads/sites/14/2011/12/GettyImages-1311222258-e1698022070508.jpg?w=500",
        "Chausie": "https://cattime.com/wp-content/uploads/sites/14/2024/01/GettyImages-1332253649-e1705250022845.jpg?w=500",
        "Cheetoh": "https://commons.wikimedia.org/wiki/Special:FilePath/Cheetoh%20cat%20chilling.png",
        "Colorpoint Shorthair": "https://commons.wikimedia.org/wiki/Special:FilePath/Colorpoint%20Shorthair.jpg",
        "Cornish Rex": "https://commons.wikimedia.org/wiki/Special:FilePath/Rex%20staredown.jpg",
        "Cymric or Manx Longhair": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Cymric_-_Norwegian_forest_cat_presentation_show_Kotka_2009-02-01_IMG_0687.JPG/440px-Cymric_-_Norwegian_forest_cat_presentation_show_Kotka_2009-02-01_IMG_0687.JPG",
        "Cyprus": "https://commons.wikimedia.org/wiki/Special:FilePath/CyprusShorthair.jpg",
        "Devon Rex": "https://commons.wikimedia.org/wiki/Special:FilePath/Devon%20Rex%20Cassini.jpeg",
        "Donskoy, or Don Sphynx": "https://commons.wikimedia.org/wiki/Special:FilePath/DSX%20World%20Premior%20RU%2ADon%20Xuk%27s%20Login%20WOW%20%2814037189016%29.jpg",
        "Dragon Li": "https://commons.wikimedia.org/wiki/Special:FilePath/Dragon%20Li%20Cat%20named%20Pipi.jpg",
        "Dwarf cat, or Dwelf": "https://commons.wikimedia.org/wiki/Special:FilePath/Elf%20cat%20small.jpg",
        "Egyptian Mau": "https://commons.wikimedia.org/wiki/Special:FilePath/RoyalNefertt%20Serket%20of%20AchetAton.jpg",
        "European Shorthair": "https://commons.wikimedia.org/wiki/Special:FilePath/Female%20European%20shorthair%20in%20cat%20show%20Helsinki%202005-07-31.JPG",
        "Exotic Shorthair": "https://commons.wikimedia.org/wiki/Special:FilePath/Ginger%20Exotic%20Shorthair.jpg",
        "Foldex[4]": "https://commons.wikimedia.org/wiki/Special:FilePath/Cachorro%20de%20Gato%20FoldEx%20%28%22Belisario%20del%20Laberinto%22%29.JPG",
        "German Rex": "https://commons.wikimedia.org/wiki/Special:FilePath/German%20Rex.jpg",
        "Havana Brown": "https://commons.wikimedia.org/wiki/Special:FilePath/Havana%20Brown%20cat.jpg",
        "Highlander": "https://commons.wikimedia.org/wiki/Special:FilePath/Highlander%20cat%20%282010%29%20Hugo%20by%20TAnthony.jpg",
        "Himalayan, or Colorpoint Persian": "https://commons.wikimedia.org/wiki/Special:FilePath/Himalayan%20cat%20Princess%20by%20Don%20Ramey%20Logan.jpg",
        "Japanese Bobtail": "https://upload.wikimedia.org/wikipedia/commons/5/56/JapaneseBobtailBlueEyedMi-ke.JPG",
        "Javanese": "https://commons.wikimedia.org/wiki/Special:FilePath/Javanese%20cat.jpg",
        "Karelian Bobtail": "https://commons.wikimedia.org/wiki/Special:FilePath/KarelianBobtail.jpg",
        "Khao Manee": "https://commons.wikimedia.org/wiki/Special:FilePath/Khaomanee%20cat.jpg",
        "Korat": "https://commons.wikimedia.org/wiki/Special:FilePath/Korat%20cat%20wikipedia.jpg",
        "Korean Bobtail": "https://commons.wikimedia.org/wiki/Special:FilePath/A%20Korean%20Cat.jpg",
        "Korn Ja": "https://commons.wikimedia.org/wiki/Special:FilePath/Korat%20cat%20wikipedia.jpg",
        "Kurilian Bobtail, or Kuril Islands Bobtail": "https://commons.wikimedia.org/wiki/Special:FilePath/Kurilian%20bobtail.JPG",
        "LaPerm": "https://commons.wikimedia.org/wiki/Special:FilePath/Laperm%20LH%20blacktortie%20white.jpg",
        "Lykoi": "https://upload.wikimedia.org/wikipedia/commons/f/fc/Dea_Chiara_De_La_Vallée_Des_Dieux_3.jpg",
        "Maine Coon": "https://commons.wikimedia.org/wiki/Special:FilePath/Maine%20Coon%20cat%20by%20Tomitheos.JPG",
        "Manx": "https://upload.wikimedia.org/wikipedia/commons/9/9b/Manx_cat_by_Karen_Weaver.jpg",
        "Mekong Bobtail": "https://commons.wikimedia.org/wiki/Special:FilePath/Mekong%20bobtail%20kittens%20tabby%20point.jpg",
        "Minskin": "https://commons.wikimedia.org/wiki/Special:FilePath/Minskin%20Kitten%20Female%20blue%20tabby%20color-pattern.jpg",
        "Munchkin": "https://commons.wikimedia.org/wiki/Special:FilePath/Longhairedmunchkin.jpg",
        "Napoleon": "https://commons.wikimedia.org/wiki/Special:FilePath/White%20Gray%20Minuet%20Cat.png",
        "Nebelung": "https://commons.wikimedia.org/wiki/Special:FilePath/Nebelung%20cat.jpg",
        "Norwegian Forest cat": "https://commons.wikimedia.org/wiki/Special:FilePath/NorwegianForestCat.jpg",
        "Ocicat": "https://commons.wikimedia.org/wiki/Special:FilePath/Ocicat.JPG",
        "Ojos Azules": "https://upload.wikimedia.org/wikipedia/commons/5/5a/Ojos_Azules_from_the_USA.jpg",
        "Oregon Rex": "https://commons.wikimedia.org/wiki/Special:FilePath/Cornish%20Rex.jpg",
        "Oriental Bicolor": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Oriental_shorthair_20070130_caroline.jpg",
        "Oriental Longhair": "https://commons.wikimedia.org/wiki/Special:FilePath/Oriental%20Longhair%20%28Javanese%2C%20Mandarin%29%2C%20Red%20Classic%20Tabby.jpg",
        "Oriental Shorthair": "https://commons.wikimedia.org/wiki/Special:FilePath/Oriental%20Shorthair.jpg",
        "PerFoldæ(Experimental Breed - WCF)": "https://commons.wikimedia.org/wiki/Special:FilePath/PerFold%20Cat%20%28%22Benito%20del%20Laberinto%22%29.jpg",
        "PerFold": "https://commons.wikimedia.org/wiki/Special:FilePath/PerFold%20Cat%20%28%22Benito%20del%20Laberinto%22%29.jpg",
        "Persian (Modern Persian Cat)": "https://commons.wikimedia.org/wiki/Special:FilePath/Persialainen.jpg",
        "Persian (Traditional Persian Cat)": "https://commons.wikimedia.org/wiki/Special:FilePath/Persian%20silver%20dollface.jpg",
        "Peterbald": "https://upload.wikimedia.org/wikipedia/commons/b/b7/Tamila_the_lilac_tabby_Peterbald_cat.jpg",
        "Pixie-bob": "https://commons.wikimedia.org/wiki/Special:FilePath/Pixiebob0001.jpg",
        "Raas": "https://commons.wikimedia.org/wiki/Special:FilePath/Kucing%20Indonesia.jpg",
        "Ragamuffin": "https://commons.wikimedia.org/wiki/Special:FilePath/RagaMuffin%20Kitten.png",
        "Ragdoll": "https://upload.wikimedia.org/wikipedia/commons/6/64/Ragdoll_from_Gatil_Ragbelas.jpg",
        "Russian Blue": "https://commons.wikimedia.org/wiki/Special:FilePath/Russian%20blue%20cat.jpg",
        "Russian White, Black and Tabby": "https://commons.wikimedia.org/wiki/Special:FilePath/White%20cat%20Krasnaya%20polyana.jpg",
        "Sam Sawet": "https://commons.wikimedia.org/wiki/Special:FilePath/Siamese%20cat.JPG",
        "Savannah": "https://upload.wikimedia.org/wikipedia/commons/c/c4/Savannah_Cat_portrait.jpg",
        "Scottish Fold": "https://upload.wikimedia.org/wikipedia/commons/5/5d/Adult_Scottish_Fold.jpg",
        "Selkirk Rex":
            "https://upload.wikimedia.org/wikipedia/en/c/c3/PolloSelkirkRex.jpg?_=20080617085419",
        "Serengeti": "https://commons.wikimedia.org/wiki/Special:FilePath/Serengetimalecat.jpg",
        "Serrade petit": "https://commons.wikimedia.org/wiki/Special:FilePath/Serrade%20petit.jpg",
        "Siamese": "https://upload.wikimedia.org/wikipedia/commons/2/25/Siam_lilacpoint.jpg",
        "Siberian": "https://commons.wikimedia.org/wiki/Special:FilePath/Siberian%20cat.JPG",
        "Singapura": "https://commons.wikimedia.org/wiki/Special:FilePath/Curious%20Singapura.jpg",
        "Snowshoe": "https://commons.wikimedia.org/wiki/Special:FilePath/Snowshoe%20%28cat%29.JPG",
        "Sokoke": "https://commons.wikimedia.org/wiki/Special:FilePath/Sokoke%20dalili.jpg",
        "Somali": "https://commons.wikimedia.org/wiki/Special:FilePath/Somali%20cat.jpg",
        "Sphynx": "https://commons.wikimedia.org/wiki/Special:FilePath/Sphynx%20-%20cat.%20img%20005.jpg",
        "Suphalak": "https://commons.wikimedia.org/wiki/Special:FilePath/Suphalak%20Female%20in%20Thailand%20named%20AumDaengManee.jpg",
        "Thai": "https://commons.wikimedia.org/wiki/Special:FilePath/%D0%A2%D0%B0%D0%B9%D1%81%D0%BA%D0%B8%D0%B9%20%D0%BA%D0%BE%D1%82%20%D0%9B%D1%83%D0%BB%D0%B0%D0%BC%D0%B5%D0%B9%20%D0%A2%D0%B0%D0%B9%D1%81%D0%BA%D0%B0%D1%8F%20%D0%9B%D0%B5%D0%B3%D0%B5%D0%BD%D0%B4%D0%B0%2C%20%D0%A7%D0%B5%D0%BC%D0%BF%D0%B8%D0%BE%D0%BD%20%D0%BC%D0%B8%D1%80%D0%B0%20%D0%BF%D0%BE%20%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B5%20WCF%2C%20%D0%BE%D0%BA%D1%80%D0%B0%D1%81%20%D0%B1%D0%BB%D1%8E%20%D0%BF%D0%BE%D0%B8%D0%BD%D1%82%2004.jpg",
        "Thai Lilac": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Korat_cat_wikipedia.jpg",
        "Tonkinese": "https://commons.wikimedia.org/wiki/Special:FilePath/Tonkinese%20Cat%20-%20Leo.jpg",
        "Toyger": "https://commons.wikimedia.org/wiki/Special:FilePath/Olympus%20Queenannecats.JPG",
        "Turkish Angora": "https://commons.wikimedia.org/wiki/Special:FilePath/Turkish%20Angora%20Cat.jpg",
        "Turkish Van": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Turkish_Van_cat_transparent_%28cropped%29.png/500px-Turkish_Van_cat_transparent_%28cropped%29.png",
        "Ukrainian Levkoy": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Ukrainian_Levkoy_cat.jpg/500px-Ukrainian_Levkoy_cat.jpg",
        "York Chocolate": "https://commons.wikimedia.org/wiki/Special:FilePath/York%20Chocolate.jpg"
    ]
}





